name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y make gcc

      - name: Build ISO
        run: make -f GNUmakefile all

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: BaboscOS.iso
          path: BaboscOS.iso
