name: Build BabOSco

on:
  push:
    branches:
      - grub
  pull_request:
    branches:
      - grub

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up cross-compiler
      run: |
        brew update
        brew install bison flex gmp mpfr libmpc texinfo
        mkdir -p $HOME/opt
        cd $HOME/opt
        curl -O https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.gz
        tar -xzvf binutils-2.36.tar.gz
        cd binutils-2.36
        mkdir build
        cd build
        ../configure --target=i686-elf --prefix="$HOME/opt/cross" --disable-nls --disable-werror
        make
        make install
        cd $HOME/opt
        curl -O https://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.gz
        tar -xzvf gcc-10.2.0.tar.gz
        cd gcc-10.2.0
        mkdir build
        cd build
        ../configure --target=i686-elf --prefix="$HOME/opt/cross" --disable-nls --enable-languages=c,c++ --without-headers
        make all-gcc
        make all-target-libgcc
        make install-gcc
        make install-target-libgcc
        echo "$HOME/opt/cross/bin" >> $GITHUB_PATH

    - name: Build Kernel
      run: |
        i686-elf-gcc -c kernel.c -o kernel.o -ffreestanding -O2 -Wall -Wextra
        i686-elf-gcc -T linker.ld -o kernel.bin -ffreestanding -O2 -nostdlib kernel.o -lgcc

    - name: Create Bootable ISO
      run: |
        mkdir -p iso/boot/grub
        cp kernel.bin iso/boot/kernel.bin
        cp grub.cfg iso/boot/grub/grub.cfg
        grub-mkrescue -o BabOSco.iso iso